import React from "react";
import { useLocation, useNavigate } from "react-router-dom";
import { motion } from "framer-motion";
import DashboardLayout from "../components/dashboard/DashboardLayout";
import WaterTestSummary from "../components/prediction/WaterTestSummary";
import RiskMatrix from "../components/prediction/RiskMatrix";
import RecommendedActions from "../components/prediction/RecommendedActions";

const containerVariants = {
  hidden: { opacity: 0 },
  visible: { opacity: 1, transition: { staggerChildren: 0.15 } }
};

const itemVariants = {
  hidden: { opacity: 0, y: 20 },
  visible: { opacity: 1, y: 0, transition: { duration: 0.5 } }
};

// PDF Export function
const exportToPDF = (reportId, waterTestSummary, predictionData) => {
  const printWindow = window.open("", "_blank");
  const riskColor = predictionData.riskLevel === "high" ? "#ef4444" : predictionData.riskLevel === "moderate" ? "#f59e0b" : "#10b981";
  
  const html = `
    <!DOCTYPE html>
    <html>
    <head>
      <title>Water Quality Report - ${reportId}</title>
      <style>
        body { font-family: Arial, sans-serif; padding: 40px; color: #333; }
        .header { text-align: center; margin-bottom: 30px; border-bottom: 2px solid #3b82f6; padding-bottom: 20px; }
        .header h1 { color: #3b82f6; margin: 0; }
        .header p { color: #666; margin-top: 5px; }
        .section { margin-bottom: 25px; }
        .section h2 { color: #1e40af; font-size: 16px; border-bottom: 1px solid #e5e7eb; padding-bottom: 8px; }
        .grid { display: grid; grid-template-columns: repeat(2, 1fr); gap: 10px; }
        .item { padding: 8px; background: #f8fafc; border-radius: 4px; }
        .item label { font-size: 11px; color: #64748b; display: block; }
        .item span { font-weight: bold; font-size: 14px; }
        .risk-box { padding: 20px; border-radius: 8px; text-align: center; margin: 20px 0; background: ${riskColor}20; border: 2px solid ${riskColor}; }
        .risk-box .level { font-size: 24px; font-weight: bold; color: ${riskColor}; text-transform: uppercase; }
        .risk-box .percent { font-size: 32px; font-weight: bold; color: ${riskColor}; }
        .diseases { display: flex; gap: 20px; justify-content: center; margin-top: 15px; }
        .disease { text-align: center; }
        .disease .name { font-size: 12px; color: #666; }
        .disease .prob { font-size: 18px; font-weight: bold; }
        .footer { margin-top: 40px; text-align: center; font-size: 11px; color: #94a3b8; }
        @media print { body { padding: 20px; } }
      </style>
    </head>
    <body>
      <div class="header">
        <h1>NeerKavach Water Quality Report</h1>
        <p>Report ID: ${reportId} | Generated: ${new Date().toLocaleDateString()}</p>
      </div>
      
      <div class="section">
        <h2>Water Test Summary</h2>
        <div class="grid">
          <div class="item"><label>Location</label><span>${waterTestSummary.locationName || "N/A"}</span></div>
          <div class="item"><label>Water Source</label><span>${waterTestSummary.waterSource || "N/A"}</span></div>
          <div class="item"><label>pH Level</label><span>${waterTestSummary.pH?.toFixed(1) || "N/A"}</span></div>
          <div class="item"><label>Turbidity</label><span>${waterTestSummary.turbidity?.toFixed(1) || "N/A"} NTU</span></div>
          <div class="item"><label>Dissolved Oxygen</label><span>${waterTestSummary.dissolvedOxygen?.toFixed(1) || "N/A"} mg/L</span></div>
          <div class="item"><label>Nitrate Level</label><span>${waterTestSummary.nitrateLevel?.toFixed(2) || "N/A"} mg/L</span></div>
          <div class="item"><label>Bacteria Count</label><span>${waterTestSummary.bacteriaCount?.toLocaleString() || "N/A"} CFU/mL</span></div>
          <div class="item"><label>Fecal Coliform</label><span>${waterTestSummary.fecalColiform || "N/A"}</span></div>
          <div class="item"><label>Temperature</label><span>${waterTestSummary.temperature?.toFixed(1) || "N/A"} °C</span></div>
          <div class="item"><label>Coordinates</label><span>${waterTestSummary.latitude || "N/A"}, ${waterTestSummary.longitude || "N/A"}</span></div>
        </div>
      </div>
      
      <div class="section">
        <h2>Disease Risk Assessment</h2>
        <div class="risk-box">
          <div class="level">${predictionData.riskLevel || "N/A"} Risk</div>
          <div class="percent">${predictionData.riskPercent || 0}%</div>
          <div class="diseases">
            ${(predictionData.diseases || []).map(d => `
              <div class="disease">
                <div class="prob">${d.probability}%</div>
                <div class="name">${d.name}</div>
              </div>
            `).join("")}
          </div>
        </div>
      </div>
      
      <div class="footer">
        <p>This report was generated by NeerKavach Water Quality Monitoring System</p>
        <p>For official use by public health authorities only</p>
      </div>
    </body>
    </html>
  `;
  
  printWindow.document.write(html);
  printWindow.document.close();
  printWindow.onload = () => {
    printWindow.print();
  };
};

// CSV Export function
const exportToCSV = (reportId, waterTestSummary, predictionData) => {
  const data = [
    ["Report ID", reportId],
    ["Location", waterTestSummary.locationName || "N/A"],
    ["Water Source", waterTestSummary.waterSource || "N/A"],
    ["pH Level", waterTestSummary.pH || "N/A"],
    ["Turbidity (NTU)", waterTestSummary.turbidity || "N/A"],
    ["Dissolved Oxygen (mg/L)", waterTestSummary.dissolvedOxygen || "N/A"],
    ["Nitrate Level (mg/L)", waterTestSummary.nitrateLevel || "N/A"],
    ["Bacteria Count (CFU/mL)", waterTestSummary.bacteriaCount || "N/A"],
    ["Fecal Coliform", waterTestSummary.fecalColiform || "N/A"],
    ["Total Coliform", waterTestSummary.totalColiform || "N/A"],
    ["Temperature (°C)", waterTestSummary.temperature || "N/A"],
    ["Latitude", waterTestSummary.latitude || "N/A"],
    ["Longitude", waterTestSummary.longitude || "N/A"],
    ["Risk Level", predictionData.riskLevel || "N/A"],
    ["Risk Percent", predictionData.riskPercent || "N/A"],
    ...(predictionData.diseases || []).map(d => [`${d.name} Likelihood (%)`, d.probability])
  ];
  
  const csv = data.map(row => row.join(",")).join("\\n");
  const blob = new Blob([csv], { type: "text/csv" });
  const url = URL.createObjectURL(blob);
  const a = document.createElement("a");
  a.href = url;
  a.download = `water-report-${reportId}.csv`;
  a.click();
  URL.revokeObjectURL(url);
};

const PredictionResult = () => {
  const location = useLocation();
  const navigate = useNavigate();

  // Get data from navigation state (passed from SubmitTest)
  const { reportId, prediction } = location.state || {};

  // Redirect if no data
  if (!prediction) {
    return (
      <DashboardLayout>
        <div className="flex flex-col items-center justify-center min-h-[400px] text-center">
          <span className="material-symbols-outlined text-6xl text-slate-300 mb-4">
            error_outline
          </span>
          <h2 className="text-xl font-bold mb-2">No Prediction Data</h2>
          <p className="text-slate-500 mb-6">
            Please submit a water test first to see predictions.
          </p>
          <button
            onClick={() => navigate("/submit-test")}
            className="px-6 py-3 bg-blue-500 text-white font-semibold rounded-xl hover:bg-blue-600 transition-colors"
          >
            Submit New Test
          </button>
        </div>
      </DashboardLayout>
    );
  }

  const waterTestSummary = prediction.waterTestSummary || {};
  const predictionData = prediction.prediction || {};

  // Format date
  const formattedDate = new Date().toLocaleDateString("en-US", {
    month: "short",
    day: "numeric",
    year: "numeric",
  });

  return (
    <DashboardLayout>
      <motion.div
        variants={containerVariants}
        initial="hidden"
        animate="visible"
        className="space-y-8"
      >
      {/* Header */}
      <motion.div variants={itemVariants} className="flex flex-col md:flex-row md:items-end justify-between gap-4">
        <div>
          <nav className="flex items-center gap-2 text-sm text-slate-500 mb-2">
            <span>Surveillance</span>
            <span className="material-symbols-outlined text-xs">
              chevron_right
            </span>
            <span>Analysis</span>
            <span className="material-symbols-outlined text-xs">
              chevron_right
            </span>
            <span className="text-blue-500 font-medium">Results</span>
          </nav>
          <h1 className="text-3xl font-bold">
            Disease Risk Prediction Results
          </h1>
          <p className="text-slate-500 dark:text-slate-400 mt-1">
            Report ID: {reportId || "N/A"} • Analyzed: {formattedDate}
          </p>
        </div>
        <div className="flex gap-3">
          <button 
            onClick={() => exportToPDF(reportId, waterTestSummary, predictionData)}
            className="flex items-center gap-2 px-4 py-2 rounded-xl border border-slate-200 dark:border-slate-700 hover:bg-slate-50 dark:hover:bg-slate-800 transition-colors"
          >
            <span className="material-symbols-outlined text-sm">download</span>
            <span>Export PDF</span>
          </button>
          <button 
            onClick={() => exportToCSV(reportId, waterTestSummary, predictionData)}
            className="flex items-center gap-2 px-4 py-2 rounded-xl border border-slate-200 dark:border-slate-700 hover:bg-slate-50 dark:hover:bg-slate-800 transition-colors"
          >
            <span className="material-symbols-outlined text-sm">table_chart</span>
            <span>Export CSV</span>
          </button>
        </div>
      </motion.div>

      {/* Content Grid */}
      <div className="grid grid-cols-1 lg:grid-cols-12 gap-8">
        {/* Left Column — Test Summary */}
        <motion.div variants={itemVariants} className="lg:col-span-4">
          <WaterTestSummary data={waterTestSummary} />
        </motion.div>

        {/* Right Column — Risk + Actions */}
        <motion.div variants={itemVariants} className="lg:col-span-8 space-y-8">
          <RiskMatrix
            diseases={predictionData.diseases || []}
            riskLevel={predictionData.riskLevel}
            riskPercent={predictionData.riskPercent}
          />
          <RecommendedActions 
            riskLevel={predictionData.riskLevel} 
            diseases={predictionData.diseases || []}
            waterTestData={waterTestSummary}
          />
        </motion.div>
      </div>
      </motion.div>
    </DashboardLayout>
  );
};

export default PredictionResult;
